-- ============================================================
-- MySQL Schema for collector-v9.js Analytics Data
-- ============================================================

-- ── Sessions ─────────────────────────────────────────────────
-- One row per unique session ID generated by the collector.
CREATE TABLE sessions (
  id            VARCHAR(64)   PRIMARY KEY,          -- _collector_sid value
  user_id       VARCHAR(255)  DEFAULT NULL,          -- set via identify()
  started_at    DATETIME      NOT NULL,
  last_seen_at  DATETIME      NOT NULL,

  -- Technographics (collected once per session)
  user_agent          TEXT          DEFAULT NULL,
  language            VARCHAR(20)   DEFAULT NULL,
  cookies_enabled     TINYINT(1)    DEFAULT NULL,
  viewport_width      SMALLINT      DEFAULT NULL,
  viewport_height     SMALLINT      DEFAULT NULL,
  screen_width        SMALLINT      DEFAULT NULL,
  screen_height       SMALLINT      DEFAULT NULL,
  pixel_ratio         FLOAT         DEFAULT NULL,
  hardware_cores      TINYINT       DEFAULT NULL,
  device_memory_gb    FLOAT         DEFAULT NULL,
  color_scheme        VARCHAR(10)   DEFAULT NULL,    -- 'light' | 'dark'
  timezone            VARCHAR(64)   DEFAULT NULL,

  -- Network (Network Information API)
  net_effective_type  VARCHAR(10)   DEFAULT NULL,    -- '4g', '3g', etc.
  net_downlink        FLOAT         DEFAULT NULL,    -- Mbps
  net_rtt             SMALLINT      DEFAULT NULL,    -- ms
  net_save_data       TINYINT(1)    DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── Pageviews ─────────────────────────────────────────────────
-- One row per pageview beacon (type = 'pageview').
CREATE TABLE pageviews (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id    VARCHAR(64)   NOT NULL,
  user_id       VARCHAR(255)  DEFAULT NULL,
  url           TEXT          NOT NULL,
  page_title    VARCHAR(512)  DEFAULT NULL,
  referrer      TEXT          DEFAULT NULL,
  collected_at  DATETIME      NOT NULL,
  error_count   SMALLINT      DEFAULT 0,

  -- Navigation Timing (ms)
  nt_dns_lookup     FLOAT DEFAULT NULL,
  nt_tcp_connect    FLOAT DEFAULT NULL,
  nt_tls_handshake  FLOAT DEFAULT NULL,
  nt_ttfb           FLOAT DEFAULT NULL,
  nt_download       FLOAT DEFAULT NULL,
  nt_dom_interactive FLOAT DEFAULT NULL,
  nt_dom_complete   FLOAT DEFAULT NULL,
  nt_load_event     FLOAT DEFAULT NULL,
  nt_fetch_time     FLOAT DEFAULT NULL,
  nt_transfer_size  INT   DEFAULT NULL,   -- bytes
  nt_header_size    INT   DEFAULT NULL,   -- bytes

  -- Web Vitals
  lcp   FLOAT DEFAULT NULL,   -- ms
  cls   FLOAT DEFAULT NULL,   -- score
  inp   FLOAT DEFAULT NULL,   -- ms

  -- Resource Summary
  total_resources INT DEFAULT NULL,

  FOREIGN KEY (session_id) REFERENCES sessions(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── Resource Breakdown (per pageview, per initiator type) ─────
-- Stores the byType summary from getResourceSummary().
CREATE TABLE pageview_resources (
  id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pageview_id     BIGINT UNSIGNED NOT NULL,
  initiator_type  VARCHAR(32) NOT NULL,   -- 'script','link','img','font','fetch','xmlhttprequest','other'
  resource_count  INT     DEFAULT 0,
  total_size      BIGINT  DEFAULT 0,      -- bytes
  total_duration  FLOAT   DEFAULT 0,      -- ms

  FOREIGN KEY (pageview_id) REFERENCES pageviews(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── Page Exit Beacons ─────────────────────────────────────────
-- One row per page_exit beacon sent on visibilitychange → hidden.
CREATE TABLE page_exits (
  id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id      VARCHAR(64) NOT NULL,
  url             TEXT        NOT NULL,
  time_on_page_ms BIGINT      DEFAULT NULL,   -- totalVisibleTime in ms
  error_count     SMALLINT    DEFAULT 0,
  exited_at       DATETIME    NOT NULL,

  -- Final Web Vitals snapshot at exit
  lcp   FLOAT DEFAULT NULL,
  cls   FLOAT DEFAULT NULL,
  inp   FLOAT DEFAULT NULL,

  FOREIGN KEY (session_id) REFERENCES sessions(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── Custom Events ─────────────────────────────────────────────
-- One row per track() call (type = 'event').
CREATE TABLE events (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id    VARCHAR(64)   NOT NULL,
  user_id       VARCHAR(255)  DEFAULT NULL,
  event_name    VARCHAR(255)  NOT NULL,
  url           TEXT          NOT NULL,
  occurred_at   DATETIME      NOT NULL,
  event_data    JSON          DEFAULT NULL,   -- arbitrary data from track()
  custom_data   JSON          DEFAULT NULL,   -- key-values from set()

  FOREIGN KEY (session_id) REFERENCES sessions(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── Errors ────────────────────────────────────────────────────
-- One row per reportError() call (type = 'error').
CREATE TABLE errors (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id    VARCHAR(64)   NOT NULL,
  url           TEXT          NOT NULL,
  occurred_at   DATETIME      NOT NULL,
  error_type    VARCHAR(32)   NOT NULL,   -- 'js-error' | 'resource-error' | 'promise-rejection'

  -- JS errors & promise rejections
  message       TEXT          DEFAULT NULL,
  source_file   TEXT          DEFAULT NULL,
  line_number   INT           DEFAULT NULL,
  column_number INT           DEFAULT NULL,
  stack_trace   TEXT          DEFAULT NULL,

  -- Resource errors
  tag_name      VARCHAR(16)   DEFAULT NULL,   -- 'IMG' | 'SCRIPT' | 'LINK'
  resource_src  TEXT          DEFAULT NULL,

  FOREIGN KEY (session_id) REFERENCES sessions(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── Custom Data (set() key-value store) ───────────────────────
-- Optional normalized table if you prefer not to store
-- customData as JSON inside pageviews/events.
CREATE TABLE custom_data (
  id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_id  VARCHAR(64)  NOT NULL,
  data_key    VARCHAR(255) NOT NULL,
  data_value  TEXT         DEFAULT NULL,
  set_at      DATETIME     NOT NULL,

  FOREIGN KEY (session_id) REFERENCES sessions(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── Indexes ───────────────────────────────────────────────────
CREATE INDEX idx_pageviews_session    ON pageviews(session_id);
CREATE INDEX idx_pageviews_collected  ON pageviews(collected_at);
CREATE INDEX idx_events_session       ON events(session_id);
CREATE INDEX idx_events_name          ON events(event_name);
CREATE INDEX idx_events_occurred      ON events(occurred_at);
CREATE INDEX idx_errors_session       ON errors(session_id);
CREATE INDEX idx_errors_type          ON errors(error_type);
CREATE INDEX idx_errors_occurred      ON errors(occurred_at);
CREATE INDEX idx_page_exits_session   ON page_exits(session_id);
CREATE INDEX idx_sessions_user        ON sessions(user_id);